// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnihyxtxtlgtwjjbpvbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuaWh5eHR4dGxndHdqamJwdmJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzQ4ODYsImV4cCI6MjA2Mzk1MDg4Nn0.ALSruzhD_B8JOiIfpM7QKobEAJVE0XEuQckf_z9ASf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);